workshop-language: nodejs
github: dudash
examples-branch: master
examples-contextdir-dcmetro: dc-metro-map
examples-contextdir-microservices: microservices

# workshop-language: ruby
# github: dudash
# examples-branch: master
# examples-contextdir-dcmetro: dc-metro-map-ruby
# examples-contextdir-microservices: microservices-ruby

# workshop-language: java
# github: dudash
# examples-branch: master
# examples-contextdir-dcmetro: dc-metro-map-java
# examples-contextdir-microservices: microservices-java